"""
update_json_conditions.py

This script will adjust JSON schemas generated by schematic to properly format names and list conditional attributes.
It also appends a reference to a registered JSON schema if provided.

Usage:
python update_json_conditions.py [JSON schema file path] 

author: orion.banks
"""

import json
import argparse
import pathlib


def generate_json_schema(input: str, ar_schema: str) -> None:
    """
    Adjusts the JSON schema to properly list conditional attributes and appends a reference to a registered schema.
    Args:
        input (str): Path to the input JSON schema file.
        ar_schema (str): URI for the registered JSON schema to reference.
    Returns:
        None
    """

    output = "".join([pathlib.Path(input).stem, "-updated.json"]) 
    
    with open(input, 'r') as i:
        model = json.load(i)

    conditions = model["allOf"]
    properties = model["properties"]

    for condition in conditions:
        for prop in condition["if"]["properties"]:
            if condition["if"]["properties"][prop]["enum"]:
                condition["if"]["properties"][prop] = {"contains": condition["if"]["properties"][prop]}
    
    for attribute in properties:
        properties[attribute]["title"] = f"{attribute}"
    
    ref_conditions = {"$ref": f"{ar_schema}"} if ar_schema is not None else None

    if ref_conditions is not None:
        conditions = conditions.append(ref_conditions)

    with open(output, 'w') as f:
        json.dump(model, f, indent=2)

    print(f"✅ JSON Schema written to {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate corrected JSON schema")
    parser.add_argument("input_path", help="Path to a JSON schema file.")
    parser.add_argument("-ar", "--ar_schema", help="URI for AR JSON schema", required=False)
    args = parser.parse_args()

    
    generate_json_schema(args.input_path, args.ar_schema)