name: publications-status-check

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install synapseclient pandas bs4 lxml

    - name: Check availability of publications
      run: |
        python utils/check_publications_status.py --send_email 3393723 3408068 3458480 3474475 3510065 3537715
      env: 
        SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
